site_name: Documentation
site_url: http://giv-gwot-vst.uni-muenster.de:3000/docs
site_description: Project documentation about the smart and mobile water gauge system of the Virtual Smart Things Group
site_author: Nicholas Schiestel, Heinrich Löwen
# site_favicon: img/favicon.ico
# Local
#site_dir: site
# Server
site_dir: /home/n_schi16/GWoT-VST/server/public/docs

repo_url: https://github.com/nicho90/GWoT-VST-Docs

pages:
- Home: index.md
- Installation guides:
    - First-Setup: installations/first-setup.md
    - Nodejs: installations/nodejs.md
    - Running Nodejs: installations/running.md
    - Bower: installations/bower.md
    - MkDocs: installations/mkdocs.md
    - Redis: installations/redis.md
    - PostgreSQL: installations/postgresql.md
    - PostGIS: installations/postgis.md
- Linux-Commands: linux-commands.md
- Architecture:
    - Components: architecture/components.md
    - Relationships: architecture/relationships.md
    - Database-Schema: architecture/database-schema.md
    - REST-API: architecture/rest-api.md
    - MQTT-Topics: architecture/mqtt-topics.md
    - Websocket-Messages: architecture/websockets.md
- Database-Schemas:
    - 1. Users: schemas/1_users.md
    - 2. Water Bodies: schemas/2_water_bodies.md
    - 3. Sensors: schemas/3_sensors.md
    - 4. Thresholds: schemas/4_thresholds.md
    - 5. Subscriptions: schemas/5_subscriptions.md
    - 6. Measurements: schemas/6_measurements.md
    - 7. Timeseries: schemas/7_timeseries.md
    - 8. Vehicles: schemas/8_vehicles.md
    - 9. Emergency Stations: schemas/9_emergency_stations.md
    - 10. Service Stations: schemas/10_service_stations.md
- WebClient:
    - Views: webclient/views.md
- Raspberry Pi:
    - Setup: rpi/setup.md
    - Wifi connection: rpi/wifi.md
    - Ultrasonic sensor: rpi/sensor.md
- About:
    - Repositories: about/repositories.md
    - Contributors: about/contributors.md
# - NewSection
    #- newPage: newSection/newPage.md
# - newSinlePage: newSinlePage.md

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: true

copyright: Copyright &copy; 2016 <a href="https://www.uni-muenster.de/Geoinformatics/">Institute for Geoinformatics, Münster</a>.
