site_name: Documentation
site_url: http://giv-gwot-vst.uni-muenster.de:3000/docs
site_description: Project documentation about the smart and mobile water gauge system of the Virtual Smart Things Group
site_author: Nicholas Schiestel, Heinrich Löwen
# site_favicon: img/favicon.ico
# Local
#site_dir: site
# Server
site_dir: /home/n_schi16/GWoT-VST/server/public/docs

repo_url: https://github.com/nicho90/GWoT-VST-Docs

pages:
- Home: index.md
- Installation guides:
    - First-Setup: installations/first-setup.md
    - Nodejs: installations/nodejs.md
    - Running Nodejs: installations/running.md
    - Bower: installations/bower.md
    - MkDocs: installations/mkdocs.md
    - Redis: installations/redis.md
    - PostgreSQL: installations/postgresql.md
    - PostGIS: installations/postgis.md
- Linux-Commands: linux-commands.md
- Architecture:
    - Components: architecture/components.md
    - Relationships: architecture/relationships.md
    - Database-Schema: architecture/database-schema.md
    - REST-API: architecture/rest-api.md
    - MQTT-Topics: architecture/mqtt-topics.md
    - Websocket-Messages: architecture/websockets.md
- Database-Schemas:
    - Users: schemas/users.md
    - Sensors: schemas/sensors.md
    - Thresholds: schemas/thresholds.md
    - Subscriptions: schemas/subscriptions.md
    - Measurements: schemas/measurements.md
    - Timeseries: schemas/timeseries.md
    - Vehicles: schemas/vehicles.md
    - Service Stations: schemas/service_stations.md
    - Emergency Stations: schemas/emergency_stations.md
- WebClient:
    - Views: webclient/views.md
- Raspberry Pi:
    - Setup: rpi/setup.md
    - Wifi connection: rpi/wifi.md
    - Ultrasonic sensor: rpi/sensor.md
- About:
    - Repositories: about/repositories.md
    - Contributors: about/contributors.md
# - NewSection
    #- newPage: newSection/newPage.md
# - newSinlePage: newSinlePage.md

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: true

copyright: Copyright &copy; 2016 <a href="https://www.uni-muenster.de/Geoinformatics/">Institute for Geoinformatics, Münster</a>.
